"""initial load

Revision ID: e56e857ce125
Revises: 
Create Date: 2018-07-27 20:42:56.987653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e56e857ce125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.add_column('budget', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('budget', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_constraint('budget_ibfk_2', 'budget', type_='foreignkey')
    op.drop_column('budget', 'operationtype_id')
    op.drop_column('budget', 'month_stamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('month_stamp', mysql.VARCHAR(charset='utf8', length=7), nullable=False))
    op.add_column('budget', sa.Column('operationtype_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('budget_ibfk_2', 'budget', 'operation_type', ['operationtype_id'], ['id'])
    op.drop_column('budget', 'start_date')
    op.drop_column('budget', 'end_date')
    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
