web:
  image: docker_web
  container_name: flask_web
  links:
    - mongodb

mysqldb:
  container_name: mysqldb
  image: mysql:5.7
  ports:
    - 3306:3306
  volumes:
    - /opt/mysql/data:/var/lib/mysql
  restart: always
  environment:
      MYSQL_ROOT_PASSWORD: xxxxxx
      MYSQL_DATABASE: fwallet
      MYSQL_USER: fwallet
      MYSQL_PASSWORD: fwallet
  
nginx:
  container_name: nginx
  image: nginx
  ports:
    - 80:80
  volumes:
    - /opt/nginx/nginx.conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - /opt/nginx/nginx.log:/var/log/nginx
  links:
    - web
