web:
  build: ./src
  container_name: fwallet_frontend
  environment:
    - FLASK_ENV=development
  links:
    - mysqldb

mysqldb:
  image: mysql:5.7
  container_name: mysqldb
  volumes:
    - /opt/mysql:/var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: xxxxxx
      MYSQL_DATABASE: fwallet
      MYSQL_USER: fwallet
      MYSQL_PASSWORD: fwallet

proxy:
  build: ./proxy
  container_name: proxy
  ports:
    - 80:80
  links:
    - web
